package prodAndes.servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class ServletIndex extends ServletTemplate{

	private static final long serialVersionUID = 1L;
	
	@Override
	public void escribirContenido(HttpServletRequest request,
			
			HttpServletResponse response) throws IOException {
		
		PrintWriter respuesta = response.getWriter();
		
		respuesta.println("<!-- Page Heading -->");
		respuesta.println("                <div class=\"row\">");
		respuesta.println("                    <div class=\"col-lg-12\">                        ");
		respuesta.println("                        <ol class=\"breadcrumb\">");
		respuesta.println("                            <li class=\"active\">");
		respuesta.println("                                <i class=\"fa fa-dashboard\"></i> Dashboard");
		respuesta.println("                            </li>");
		respuesta.println("                        </ol>");
		respuesta.println("                    </div>");
		respuesta.println("                </div>");
		respuesta.println("                <!-- /.row -->");
		respuesta.println("                ");
		respuesta.println("                <!-- /.row -->");
		respuesta.println("");
		respuesta.println("                <div class=\"row\">");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-primary\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-table fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RFC1</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RFC1.html\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Consultar las existencias de Materiales</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-green\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-table fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RFC2</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RFC2.html\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Consultar un Material</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-yellow\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-table fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RFC5</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RFC5.htm\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Consultar Pedidos</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-red\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-table fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RFC6</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RFC6.htm\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Consultar Clientes</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-primary\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-table fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RFC7</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RFC7.htm\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Consultar Proveedores</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-green\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-edit fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RF10</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RF10.html\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Registrar ejecucion de etapa</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-yellow\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-edit fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RF11</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RF11.html\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Registrar Llegada Material</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                </div>");
		respuesta.println("                <!-- /.row -->");
		respuesta.println("				<div class=\"row\">");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-red\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-edit fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RF12</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RF12.html\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Registrar Pedido de Productos</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-primary\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-edit fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RF13</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RF13.htm\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Cancelar Pedido de Productos</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-green\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-edit fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RF14</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RF14.html\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Registrar Entrega de Pedido de Productos</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                    <div class=\"col-lg-12\">");
		respuesta.println("                        <div class=\"panel panel-yellow\">");
		respuesta.println("                            <div class=\"panel-heading\">");
		respuesta.println("                                <div class=\"row\">");
		respuesta.println("                                    <div class=\"col-xs-3\">");
		respuesta.println("                                        <i class=\"fa fa-edit fa-5x\"></i>");
		respuesta.println("                                    </div>");
		respuesta.println("                                    <div class=\"col-xs-9 text-right\">");
		respuesta.println("                                        <div class=\"huge\">RF17</div>");
		respuesta.println("                                    </div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </div>");
		respuesta.println("                            <a href=\"RF17.htm\">");
		respuesta.println("                                <div class=\"panel-footer\">");
		respuesta.println("                                    <span class=\"pull-left\">Reportar cambio de estado de una estacion de produccion</span>");
		respuesta.println("                                    <span class=\"pull-right\"><i class=\"fa fa-arrow-circle-right\"></i></span>");
		respuesta.println("                                    <div class=\"clearfix\"></div>");
		respuesta.println("                                </div>");
		respuesta.println("                            </a>");
		respuesta.println("                        </div>");
		respuesta.println("                    </div>");
		respuesta.println("                 </div>");


		
	}

}
